---

- name: be sure nginx is installed
  apt: pkg=nginx state=installed
  tags: nginx

- name: write nginx.conf
  action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags: nginx

- name: make sure the log directory is there
  file: path=/var/log/nginx owner=www-data group=www-data mode=0755 state=directory
  tags: nginx

- name: be sure nginx is running and enabled
  service: name=nginx state=running enabled=yes
  tags: nginx

#- include: git.yml
