- name: Add the sensu repo
  lineinfile: dest=/etc/apt/sources.list.d/sensu.list regexp="sensuapp.org" line='deb http://repos.sensuapp.org/apt sensu main' create=yes
  register: aptrepo

- name: Add the sensu aptkey
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present

- name: Refresh the apt cache
  apt: update_cache=yes
  when: aptrepo.changed

- name: Install the sensu and ruby packages
  apt: name=$item state=latest force=yes
  with_items:
    - ruby
    - sensu

- name: Copy over the config file
  template: src=config.json dest=/etc/sensu/config.json owner=sensu group=sensu mode=0640
  notify: restart sensuserver

- name: Create the directory
  file: path=/etc/sensu/ssl owner=sensu group=sensu mode=0750 state=directory

- name: Copy over the ssl files (again)
  copy: src=$item.pem dest=/etc/sensu/ssl/ owner=sensu group=sensu mode=0640
  with_items:
    - client_cert
    - client_key
  notify: 
    - restart sensuserver

- name: Copy over the nginx stuff for the sensu vhost
  template: src=sensu.conf dest=/etc/nginx/sites-available/sensu.conf owner=root group=root mode=0640

- name: put the link into sites-enabled
  file: src=/etc/nginx/sites-available/sensu.conf dest=/etc/nginx/sites-enabled/sensu.conf state=link

- name: copy over the graphite configuration stuff
  template: src={{ item }} dest=/etc/sensu/conf.d/{{item }} owner=sensu group=sensu mode=0750
  with_items:
    - graphite_tcp.json
    - handler_graphite.json

- name: copy over the sensu handlers
  copy: src={{ item }} dest=/etc/sensu/conf.d/{{item }} owner=sensu group=sensu mode=0750
  with_items:
    - handler_flowdock.json
    - handler_default.json
    - handler_mail-ses.json

#- name: install some libs (just ruby-flowdock)
# apt: name=$item state=latest force=yes
#  with_items:
#    - ruby-flowdock