---
- name: Install mysql and the perl library
  apt: pkg={{ item }} state=present
  with_items:
  - mysql-common
  - mysql-server
  - libdbi-perl
  - python-dev 
  - libmysqlclient-dev
  - python-pip

- name: install mysql python library
  pip: name=MySQL-python

- name: start mysql
  action: service name=mysql state=started

- name: update the root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
  - '{{ ansible_hostname }}'
  - 127.0.0.1
  - ::1
  - localhost

- name: copy .my.cnf file with root password (peculiarity of ansible mysql user ?)
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: delete the anon user
  action: mysql_user user="" host="$server_hostname" state="absent"

- name: delete the anon user
  action: mysql_user user="" state="absent"

- name: remove the test db
  action: mysql_db db=test state=absent