---
- name: Install mysql and the perl library
  action: yum name={{ item }}
  with_items:
  - MySQL-python
  - mysql
  - mysql-server
  - libdbd-mysql-perl

- name: start mysql
  action: service name=mysqld state=started

- name: update the root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
  - {{ ansible_hostname }}
  - 127.0.0.1
  - ::1
  - localhost

- name: copy .my.cnf file with root password (peculiarity of ansible mysql user ?)
  template: src=templates/root/.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: delete the anon user
  action: mysql_user user="" host="$server_hostname" state="absent"

- name: delete the anon user
  action: mysql_user user="" state="absent"

- name: remove the test db
  action: mysql_db db=test state=absent