- name: install ruby-dev
  apt: pkg=ruby-dev state=latest force=yes

- name: install sensu-plugin gem
  gem: name=sensu-plugin state=latest

- name: install check plugins
  copy: src={{ item }} dest=/etc/sensu/plugins/{{ item }} mode=0755
  with_items:
    - check_procs.rb
    - check_disk.rb

- name: install check json files
  copy: src={{ item }} dest=/etc/sensu/conf.d/{{ item }} mode=0644
  with_items:
    - check_cron.json
    - check_disk.json

- name: start sensu client
  service: name=sensu-client state=started