#- name: add universe#
#  apt_repository: repo='deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe' state=present

- name: install python-apt
  apt: pkg=python-apt

- name: Refresh apt cache
  apt: update_cache=yes

- name: install graphite framework packages
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - gunicorn
    - supervisor
    - graphite-web
    - graphite-carbon

- name: change the line to setup carbon cache
  lineinfile: dest=/etc/default/graphite-carbon regexp="CARBON_CACHE_ENABLED=false" line="CARBON_CACHE_ENABLED=true"

- name: enable the carbon-cache server
  service: name=carbon-cache state=started enabled=yes
  notify: start carbon

- name: Copy over the graphite.local_settings file
  copy: src=graphite.local_settings.py dest=/opt/graphite/webapp/graphite/local_settings.py

- name: run syncdb
  django_manage: command=syncdb app_path=/opt/graphite/webapp/graphite/
  
- name: copy over the supervisor files
  copy: src=graphite.supervisor dest=/etc/supervisor/conf.d/graphite-web.conf
  notify: update supervisor

- name: change ownership
  file: path=/opt/graphite/storage/ owner=www-data group=www-data state=directory recurse=yes 