---

- name: be sure ntp is installed
  apt: pkg=ntp state=installed
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntp
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp

- name: add gwyn file to /etc/sudoers.dest
  copy: src=/etc/ansible/roles/common/templates/gwyn dest=/etc/sudoers.d owner=root group=root mode=644 backup=yes
  tags: sudoers

- name: change sudoers.d line in /etc/sudoers
  lineinfile: dest=/etc/sudoers regexp=/etc/sudoers.d$ line='#includedir /etc/sudoers.d'
  tags: sudoers

- name: install sysstat
  apt: pkg=sysstat state=installed
  tags: sysstat

- name: change sysstat to enabled
  lineinfile: dest=/etc/default/sysstat regexp=^ENABLED line=ENABLED="true"
  tags: sysstat

- name: restart sysstat
  service: name=sysstat state=running enabled=yes
  tags: sysstat

